### PR TITLE
Add help option to RemoteDesktop

### PR DESCRIPTION
**Pull request by DarkmatterVale**
In this PR, I add a simple "--help" option for RemoteDesktop. I keep the documentation pretty simple, but it is enough to inform the user how to use RemoteDesktop.

### CODE REVIEW

**Comment by waddlesplash** [comment]
We don't accept pull requests.

**Comment by DarkmatterVale** [comment]
Sorry, did not know that.

How should I get my changes added then? Should I create a patch? If so, where do I send the patch?

**Comment by waddlesplash** [comment]
Did you read the repository description?
>(Pull requests will be ignored; patches may be sent to https://dev.haiku-os.org).

**Comment by DarkmatterVale** [comment]
Found the page, thank you.

**Pull request closed without merging**
