### PR TITLE
style cleanup no functional change

### PR DESCRIPTION
**Pull request by asutoshgha**
just made the code more understandable and less confusing at line number 22.

### CODE REVIEW

**Comment by korli** [comment]
We don't accept PRs here, use Gerrit instead.

**Comment by kallisti5** [comment]
Hello @asutoshgha !   Changes are accepted at https://review.haiku-os.org.    Thanks!

**Comment by kallisti5** [comment]
also, this change would most likely not be accepted.   The line is split because we have a strict 80-character limit on length.

**Comment by asutoshgha** [comment]
I will follow it from next time I didn't knew about it.
Where is the shutdown part of the haiku code located and where are the
images for various Icons located in haiku?

**Pull request closed without merging**
